/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Admins: () => import('#controllers/admins_controller'),
  Chapters: () => import('#controllers/chapters_controller'),
  Course: () => import('#controllers/course_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
